markdown: kramdown
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-include-cache
relative_links:
  enabled: true
  collections: true
kramdown:
  toc_levels: 2..3
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# hide the RSS Feed link in the footer
atom_feed:
  hide: true
