plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - LK_CorrectionSymbols.md 
  - checklists/LK_Checklist_Comment.md
  - checklists/LK_Checklist_InformativeWriting.md
  - checklists/LK_Checklist_PersonalEmail_A1.md

